# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "05bfa7729e53772a190b4e79d0e2d241"
name = "app-uniware-UI"
handle = "app-uniware-ui"
application_url = "https://shopify-node.unicommerce.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "uniwaredevstore.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_fulfillments,read_inventory,read_locations,read_merchant_managed_fulfillment_orders,read_orders,read_products,read_third_party_fulfillment_orders,write_assigned_fulfillment_orders,write_fulfillments,write_merchant_managed_fulfillment_orders,write_third_party_fulfillment_orders"

[auth]
redirect_urls = [
  "https://shopify-node.unicommerce.com/auth/callback",
  "https://shopify-node.unicommerce.com/auth/shopify/callback",
  "https://shopify-node.unicommerce.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false