# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "05bfa7729e53772a190b4e79d0e2d241"
name = "app-uniware-UI"
handle = "app-uniware-ui"
application_url = "https://b6bf-203-189-255-51.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "uniwaredevstore.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://b6bf-203-189-255-51.ngrok-free.app/auth/callback",
  "https://b6bf-203-189-255-51.ngrok-free.app/auth/shopify/callback",
  "https://b6bf-203-189-255-51.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
